name: CI Build and Publish â€“ Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  ci-release:
    uses: ./.github/workflows/ci-build-publish.yml
    secrets: inherit
    with:
      environment: dev
      is_release: true
      is_publish: true
      trigger_docker: true
      trigger_deploy: true
